"""Added video and video snapshot tables

Revision ID: 0393cd1416a7
Revises:
Create Date: 2025-12-11 22:53:40.056495

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0393cd1416a7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "videos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("creator_id", sa.String(), nullable=True),
        sa.Column("video_created_at", sa.DateTime(), nullable=True),
        sa.Column("views_count", sa.Integer(), nullable=True),
        sa.Column("likes_count", sa.Integer(), nullable=True),
        sa.Column("comments_count", sa.Integer(), nullable=True),
        sa.Column("reports_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_videos")),
    )
    op.create_table(
        "video_snapshots",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("video_id", sa.UUID(), nullable=True),
        sa.Column("views_count", sa.Integer(), nullable=True),
        sa.Column("likes_count", sa.Integer(), nullable=True),
        sa.Column("comments_count", sa.Integer(), nullable=True),
        sa.Column("reports_count", sa.Integer(), nullable=True),
        sa.Column("delta_views_count", sa.Integer(), nullable=True),
        sa.Column("delta_likes_count", sa.Integer(), nullable=True),
        sa.Column("delta_comments_count", sa.Integer(), nullable=True),
        sa.Column("delta_reports_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["video_id"], ["videos.id"], name=op.f("fk_video_snapshots_video_id_videos")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_snapshots")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video_snapshots")
    op.drop_table("videos")
    # ### end Alembic commands ###
